### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by rogxo** [ekknod/acdrv#6]
Windows 10 Kernel Version 19041 MP (2 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Edition build lab: 19041.1.amd64fre.vb_release.191206-1406
Kernel base = 0xfffff805`40605000 PsLoadedModuleList = 0xfffff805`4122f290
Debug session time: Mon Oct 23 03:42:42.016 2023 (UTC + 8:00)
System Uptime: 0 days 0:02:02.744
[driver.sys] Running
[driver.sys] [System:System][1AD000][FFFFF80540A05EC6] exception was caught
[driver.sys] [System:System][1AD000][FFFFF80540A05EC6] exception was caught
[driver.sys] [System:System][1AD000][FFFFF80540A05EC6] exception was caught
[driver.sys] [System:System][1AD000][FFFFF80540A05EC6] exception was caught
[driver.sys] [System:System][1AD000][FFFFF80540A05EC6] exception was caught
[driver.sys] [System:System][1AD000][FFFFF80540A05EC6] exception was caught
[driver.sys] [System:System][1AD000][FFFFF80540A05EC6] exception was caught
KDTARGET: Refreshing KD connection
[driver.sys] [System:System][1AD000][FFFFF805409FDFA0] exception was caught
[driver.sys] [System:System][1AD000][FFFFF805409FDFA0] exception was caught
[driver.sys] [System:System][1AD000][FFFFF805409FDFA0] exception was caught
[driver.sys] [System:System][1AD000][FFFFF805409FDFA0] exception was caught
[driver.sys] [System:System][1AD000][FFFFF805409FDFA0] exception was caught
[driver.sys] [System:System][1AD000][FFFFF805409FDFA0] exception was caught
[driver.sys] [System:System][1AD000][FFFFF805409FDFA0] exception was caught
[driver.sys] [System:System][1AD000][FFFFF805409FDFA0] exception was caught
[driver.sys] [System:System][1AD000][FFFFF805409FDFA0] exception was caught
[driver.sys] [System:System][1AD000][FFFFF805409FDFA0] exception was caught
[driver.sys] [System:System][1AD000][FFFFF805409FDFA0] exception was caught
[driver.sys] [System:System][1AD000][FFFFF805409FDFA0] exception was caught
[driver.sys] [System:System][1AD000][FFFFF805409FDFA0] exception was caught
[driver.sys] [System:System][1AD000][FFFFF805409FDFA0] exception was caught
Break instruction exception - code 80000003 (first chance)

A fatal system error has occurred.

For analysis of this file, run !analyze -v
nt!DbgBreakPointWithStatus:
fffff805`40a05e70 cc              int     3
0: kd> k
 # Child-SP          RetAddr               Call Site
00 fffff805`434bf578 fffff805`40b17f02     nt!DbgBreakPointWithStatus
01 fffff805`434bf580 fffff805`40b178ad     nt!KiBugCheckDebugBreak+0x12
02 fffff805`434bf5e0 fffff805`409fe0a7     nt!KeBugCheck2+0xd0d
03 fffff805`434bfcf0 fffff805`40a0ff69     nt!KeBugCheckEx+0x107
04 fffff805`434bfd30 fffff805`40a0ad83     nt!KiBugCheckDispatch+0x69
05 fffff805`434bfe70 fffff805`40a0be10     nt!KiDoubleFaultAbort+0x2c3
06 fffff805`434b2f80 fffff805`40a06a96     nt!KiPageFault+0x10
07 fffff805`434b3118 fffff805`4087b5dd     nt!_chkstk+0x36
08 fffff805`434b3130 fffff805`40a100ac     nt!KiDispatchException+0xed
09 fffff805`434b32f0 fffff805`40a0eda2     nt!KiExceptionDispatch+0x12c
0a fffff805`434b34d0 fffff805`40a05e95     nt!KiDebugServiceTrap+0x322
0b fffff805`434b3668 fffff805`4096840b     nt!DebugPrint+0x15
0c fffff805`434b3670 fffff805`409828e0     nt!vDbgPrintExWithPrefixInternal+0x13b
0d fffff805`434b3770 fffff805`5f1a19da     nt!DbgPrintEx+0x30
0e fffff805`434b37c0 fffff805`40fba216     driver!hooks::exception::KdTrapHook+0x11a [E:\Project\CodeProject\SourceCode\acdrv\main.cpp @ 237] 
0f fffff805`434b3860 fffff805`40fbc81c     nt!KdExitDebugger+0x86
10 fffff805`434b3890 fffff805`40fbdb4f     nt!KdpPrint+0x154
11 fffff805`434b38e0 fffff805`4087ba79     nt!KdpTrap+0x12f
12 fffff805`434b3930 fffff805`4087b667     nt!KdTrap+0x2d
13 fffff805`434b3970 fffff805`40a100ac     nt!KiDispatchException+0x177
14 fffff805`434b4030 fffff805`40a0eda2     nt!KiExceptionDispatch+0x12c
15 fffff805`434b4210 fffff805`40a05e95     nt!KiDebugServiceTrap+0x322
16 fffff805`434b43a8 fffff805`4096840b     nt!DebugPrint+0x15
17 fffff805`434b43b0 fffff805`409828e0     nt!vDbgPrintExWithPrefixInternal+0x13b
18 fffff805`434b44b0 fffff805`5f1a19da     nt!DbgPrintEx+0x30
19 fffff805`434b4500 fffff805`40fba216     driver!hooks::exception::KdTrapHook+0x11a [E:\Project\CodeProject\SourceCode\acdrv\main.cpp @ 237] 
1a fffff805`434b45a0 fffff805`40fbc81c     nt!KdExitDebugger+0x86
1b fffff805`434b45d0 fffff805`40fbdb4f     nt!KdpPrint+0x154
1c fffff805`434b4620 fffff805`4087ba79     nt!KdpTrap+0x12f
1d fffff805`434b4670 fffff805`4087b667     nt!KdTrap+0x2d
1e fffff805`434b46b0 fffff805`40a100ac     nt!KiDispatchException+0x177
1f fffff805`434b4d70 fffff805`40a0eda2     nt!KiExceptionDispatch+0x12c
20 fffff805`434b4f50 fffff805`40a05e95     nt!KiDebugServiceTrap+0x322
21 fffff805`434b50e8 fffff805`4096840b     nt!DebugPrint+0x15
22 fffff805`434b50f0 fffff805`409828e0     nt!vDbgPrintExWithPrefixInternal+0x13b
23 fffff805`434b51f0 fffff805`5f1a19da     nt!DbgPrintEx+0x30
24 fffff805`434b5240 fffff805`40fba216     driver!hooks::exception::KdTrapHook+0x11a [E:\Project\CodeProject\SourceCode\acdrv\main.cpp @ 237] 
25 fffff805`434b52e0 fffff805`40fbc81c     nt!KdExitDebugger+0x86
26 fffff805`434b5310 fffff805`40fbdb4f     nt!KdpPrint+0x154
27 fffff805`434b5360 fffff805`4087ba79     nt!KdpTrap+0x12f
28 fffff805`434b53b0 fffff805`4087b667     nt!KdTrap+0x2d
29 fffff805`434b53f0 fffff805`40a100ac     nt!KiDispatchException+0x177
2a fffff805`434b5ab0 fffff805`40a0eda2     nt!KiExceptionDispatch+0x12c
2b fffff805`434b5c90 fffff805`40a05e95     nt!KiDebugServiceTrap+0x322
2c fffff805`434b5e28 fffff805`4096840b     nt!DebugPrint+0x15
2d fffff805`434b5e30 fffff805`409828e0     nt!vDbgPrintExWithPrefixInternal+0x13b
2e fffff805`434b5f30 fffff805`5f1a19da     nt!DbgPrintEx+0x30
2f fffff805`434b5f80 fffff805`40fba216     driver!hooks::exception::KdTrapHook+0x11a [E:\Project\CodeProject\SourceCode\acdrv\main.cpp @ 237] 
30 fffff805`434b6020 fffff805`40fbc81c     nt!KdExitDebugger+0x86
31 fffff805`434b6050 fffff805`40fbdb4f     nt!KdpPrint+0x154
32 fffff805`434b60a0 fffff805`4087ba79     nt!KdpTrap+0x12f
33 fffff805`434b60f0 fffff805`4087b667     nt!KdTrap+0x2d
34 fffff805`434b6130 fffff805`40a100ac     nt!KiDispatchException+0x177
35 fffff805`434b67f0 fffff805`40a0eda2     nt!KiExceptionDispatch+0x12c
36 fffff805`434b69d0 fffff805`40a05e95     nt!KiDebugServiceTrap+0x322
37 fffff805`434b6b68 fffff805`4096840b     nt!DebugPrint+0x15
38 fffff805`434b6b70 fffff805`409828e0     nt!vDbgPrintExWithPrefixInternal+0x13b
39 fffff805`434b6c70 fffff805`5f1a19da     nt!DbgPrintEx+0x30
3a fffff805`434b6cc0 fffff805`40fba216     driver!hooks::exception::KdTrapHook+0x11a [E:\Project\CodeProject\SourceCode\acdrv\main.cpp @ 237] 
3b fffff805`434b6d60 fffff805`40fbc81c     nt!KdExitDebugger+0x86
3c fffff805`434b6d90 fffff805`40fbdb4f     nt!KdpPrint+0x154
3d fffff805`434b6de0 fffff805`4087ba79     nt!KdpTrap+0x12f
3e fffff805`434b6e30 fffff805`4087b667     nt!KdTrap+0x2d
3f fffff805`434b6e70 fffff805`40a100ac     nt!KiDispatchException+0x177
40 fffff805`434b7530 fffff805`40a0eda2     nt!KiExceptionDispatch+0x12c
41 fffff805`434b7710 fffff805`40a05e95     nt!KiDebugServiceTrap+0x322
42 fffff805`434b78a8 fffff805`4096840b     nt!DebugPrint+0x15
43 fffff805`434b78b0 fffff805`409828e0     nt!vDbgPrintExWithPrefixInternal+0x13b
44 fffff805`434b79b0 fffff805`5f1a19da     nt!DbgPrintEx+0x30
45 fffff805`434b7a00 fffff805`40fba216     driver!hooks::exception::KdTrapHook+0x11a [E:\Project\CodeProject\SourceCode\acdrv\main.cpp @ 237] 
46 fffff805`434b7aa0 fffff805`40fbc81c     nt!KdExitDebugger+0x86
47 fffff805`434b7ad0 fffff805`40fbdb4f     nt!KdpPrint+0x154
48 fffff805`434b7b20 fffff805`4087ba79     nt!KdpTrap+0x12f
49 fffff805`434b7b70 fffff805`4087b667     nt!KdTrap+0x2d
4a fffff805`434b7bb0 fffff805`40405819     nt!KiDispatchException+0x177
4b fffff805`434b8270 00000000`00000000     0xfffff805`40405819

A call loop occured...

**Comment by ekknod** [comment]
Thank you for information, I will update this project soon and find out what exactly caused your issue
